### ISSUE TITLE
Python version

### ISSUE THREAD

**Issue by MTrab** [ludeeus/container#301]
Any specific reason for the devcontainer to be at Python 3.10 when Home Assistant it self is build for 3.9?

Just ran into an issue where `var:str | None` caused some errors, as this syntax isn't valid in version 3.9

**Comment by ludeeus** [comment]
That's one simple reason, I follow the development of the runtimes and not Home Assistant.
Also, that syntax is valid since 3.7, but requires `from __future__ import annotations` until 3.11 (That syntax is heavily used in the Home Assistant codebase as well)

I do not know when I started building 3.10, but the older builds should have 3.9 or even 3.8 https://github.com/ludeeus/container/pkgs/container/devcontainer%2Fintegration/versions
